version: 3.9

services:
  reading-progress-tracker:
    image: reading-progress-tracker:latest
    ports:
      - "${READING_PROGRESS_TRACKER_PORT}:8080"
    environment:
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - READING_PROGRESS_TRACKER_PORT=${READING_PROGRESS_TRACKER_PORT}
      - READING_PROGRESS_TRACKER_FRONTEND_URL=${READING_PROGRESS_TRACKER_FRONTEND_URL}
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
