version: 3.9

services:
  reading-progress-tracker:
    image: reading-progress-tracker:latest
    ports:
      - "${READING_PROGRESS_TRACKER_PORT}:8080"
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
